<a href="https://colab.research.google.com/github/Avupati-Sai-Likhitha/Image-Classification/blob/main/Image_Classification_using_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing libraries and modules**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from skimage.io import imread
from skimage.transform import resize
import os

**Preprocessing Images**

In [ ]:
dir = '/content/drive/MyDrive/ML/Images'

categories = ['Mango','Brinjal'] 
target = []
images = []
flat_data = []

for i in categories:
  num = categories.index(i)
  path = os.path.join(dir,i)
  for img in os.listdir(path):
    img_array = imread(os.path.join(path,img))
    img_resized = resize(img_array,(150,150,3)) 
    # Flattening images
    flat_data.append(img_resized.flatten())
    images.append(img_resized)
    target.append(num)

flat_data = np.array(flat_data)
target = np.array(target)
images = np.array(images)

In [ ]:
print(flat_data[0])
print(target)

[0.82745098 0.8627451  0.65294118 ... 0.54117647 0.42745098 0.39019608]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [ ]:
unique, count = np.unique(target,return_counts=True)
plt.bar(categories,count)

<BarContainer object of 2 artists>

**Creating Dataframe**

In [ ]:
df = pd.DataFrame(flat_data)
df['Target'] = target
df.head()

0         1         2         3  ...     67497     67498     67499  Target
0  0.827451  0.862745  0.652941  0.839216  ...  0.541176  0.427451  0.390196       0
1  0.121569  0.121569  0.121569  0.199722  ...  0.835294  0.831373  0.850980       0
2  0.866013  0.408876  0.248521  0.566203  ...  0.443137  0.344444  0.262745       0
3  0.854902  0.768627  0.705882  0.850980  ...  0.837255  0.890196  0.898039       0
4  0.418954  0.321569  0.007843  0.427451  ...  0.596078  0.478431  0.233333       0

[5 rows x 67501 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(flat_data,target,test_size=0.3,random_state=109)

**Applying Algorithm**

In [ ]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

**Finding best parameters using GridSearchCV**

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
param = [
         {'C' : [1,10,100,1000], 'kernel' : ['linear']},
         {'C' : [1,10,100,1000], 'gamma' : [0.001,0.0001], 'kernel' : ['rbf']}
]
svc=svm.SVC(probability=True)
clf=GridSearchCV(svc,param)
clf.fit(x_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
y_pred=clf.predict(x_test)
y_pred

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0])

In [ ]:
y_test

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
accuracy_score(y_pred,y_test)

1.0

In [ ]:
confusion_matrix(y_pred,y_test)

array([[11,  0],
       [ 0,  7]])

In [ ]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00         7

    accuracy                           1.00        18
   macro avg       1.00      1.00      1.00        18
weighted avg       1.00      1.00      1.00        18



**Saving model**

In [ ]:
import pickle
pickle.dump(clf,open('image_model.p','wb'))

In [ ]:
model = pickle.load(open('image_model.p','rb'))

**Testing a new image**

In [ ]:
flat_data = []
url = input('Enter the URL for mango/brinjal images : ')
img = imread(url)
img_resized = resize(img,(150,150,3))
flat_data.append(img_resized.flatten())
flat_data = np.array(flat_data)
print(img.shape)
plt.imshow(img_resized)
y_out = model.predict(flat_data)
y_out = categories[y_out[0]]
print(f'Predicted output -- {y_out}')

Enter the URL for mango/brinjal images : https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2kobii_jxg6ZZXEvghsNp3t9PGHtq2MGs1w&usqp=CAU
(225, 225, 3)
Predicted output -- Brinjal
